name: Waka Readme test

on:
 # push:
    #branches:
      #- master
  #pull_request:
   # branches:
     # - master
  schedule:
    # Runs at 12am IST
    #- cron: '30 18 * * *'
    #- cron: '*/1 * * * *'
    - cron: '0 */6 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "True"
          SHOW_UPDATED_DATE: "True"
