name: Wakatime README

on:
 # push:
    #branches:
      #- master
  #pull_request:
   # branches:
     # - master
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "True"
          SHOW_UPDATED_DATE: "True"
          IGNORED_REPOS: "powercasgamer, .github"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          
